spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.179.128:10086/db_leizq_docker?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: ENC(0FKn8SdFWWokipNxnXuHDQ==)
    password: ENC(J9hyi3H2U0Bch+oMongOHb8Qw5La11rE)
    druid:
      #aop-patterns: com.richinfo.boot.*
      filter:
        stat:
          slow-sql-millis: 3000
          enabled: true
          log-slow-sql: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
            insert-allow: true
            delete-allow: false
            update-where-alay-true-check: true

      stat-view-servlet:
        enabled: true
        login-username: leizq
        login-password: ENC(J9hyi3H2U0Bch+oMongOHb8Qw5La11rE)
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
jasypt:
  encryptor:
    password: ysyhl9daysflzx3000c
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml